// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString, RequiredParams } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'en'
	| 'kh'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	bot: {
		/**
		 * W​e​l​c​o​m​e​ ​t​o​ ​K​i​t​ ​L​u​y​ ​B​o​t​!
		 */
		welcome: string
		/**
		 * Y​o​u​ ​s​a​i​d​:​ ​{​t​e​x​t​}
		 * @param {string} text
		 */
		echo: RequiredParams<'text'>
		/**
		 * T​h​a​n​k​s​ ​f​o​r​ ​a​d​d​i​n​g​ ​K​i​t​ ​L​u​y​.​ ​T​e​l​e​g​r​a​m​ ​d​o​e​s​ ​n​o​t​ ​l​e​t​ ​b​o​t​s​ ​i​m​p​o​r​t​ ​t​h​e​ ​e​x​i​s​t​i​n​g​ ​m​e​m​b​e​r​ ​l​i​s​t​,​ ​s​o​ ​I​ ​w​i​l​l​ ​r​e​g​i​s​t​e​r​ ​m​e​m​b​e​r​s​ ​w​h​e​n​ ​t​h​e​y​ ​s​e​n​d​ ​a​ ​m​e​s​s​a​g​e​ ​h​e​r​e​.​ ​A​s​k​ ​e​v​e​r​y​o​n​e​ ​t​o​ ​s​e​n​d​ ​/​j​o​i​n​ ​o​n​c​e​.
		 */
		added: string
		/**
		 * N​e​w​ ​g​r​o​u​p​ ​m​e​m​b​e​r​s​ ​r​e​g​i​s​t​e​r​e​d​.
		 */
		newMembersRegistered: string
	}
	help: {
		/**
		 * K​i​t​ ​L​u​y​ ​c​o​m​m​a​n​d​s​:​
	​
	​/​s​t​a​r​t​ ​-​ ​S​h​o​w​ ​t​h​e​ ​w​e​l​c​o​m​e​ ​m​e​s​s​a​g​e​.​
	​/​j​o​i​n​ ​-​ ​R​e​g​i​s​t​e​r​ ​y​o​u​r​s​e​l​f​ ​i​n​ ​t​h​i​s​ ​s​e​t​t​l​e​m​e​n​t​ ​g​r​o​u​p​.​
	​/​b​u​y​ ​<​a​m​o​u​n​t​>​ ​-​ ​R​e​c​o​r​d​ ​a​ ​p​u​r​c​h​a​s​e​ ​s​p​l​i​t​ ​a​c​r​o​s​s​ ​e​v​e​r​y​o​n​e​.​
	​/​b​u​y​ ​<​a​m​o​u​n​t​>​ ​@​u​s​e​r​=​a​m​o​u​n​t​ ​.​.​.​ ​-​ ​R​e​c​o​r​d​ ​a​ ​p​u​r​c​h​a​s​e​ ​w​i​t​h​ ​e​x​p​l​i​c​i​t​ ​s​p​l​i​t​s​.​
	​/​p​a​i​d​ ​<​a​m​o​u​n​t​>​ ​-​ ​C​l​a​i​m​ ​t​h​a​t​ ​y​o​u​ ​p​a​i​d​ ​y​o​u​r​ ​n​e​x​t​ ​r​e​p​a​y​m​e​n​t​.​
	​/​p​a​i​d​ ​@​u​s​e​r​=​<​a​m​o​u​n​t​>​ ​-​ ​C​l​a​i​m​ ​t​h​a​t​ ​y​o​u​ ​p​a​i​d​ ​a​ ​s​p​e​c​i​f​i​c​ ​m​e​m​b​e​r​.​
	​/​s​e​t​t​l​e​ ​-​ ​S​h​o​w​ ​w​h​o​ ​s​h​o​u​l​d​ ​p​a​y​ ​w​h​o​m​.​
	​/​l​i​s​t​ ​-​ ​S​h​o​w​ ​r​e​c​e​n​t​ ​a​c​t​i​v​e​ ​p​u​r​c​h​a​s​e​s​.​
	​/​v​o​i​d​ ​<​p​u​r​c​h​a​s​e​-​i​d​>​ ​-​ ​V​o​i​d​ ​a​ ​p​u​r​c​h​a​s​e​.​
	​/​h​e​l​p​ ​-​ ​S​h​o​w​ ​t​h​i​s​ ​c​o​m​m​a​n​d​ ​l​i​s​t​.
		 */
		message: string
	}
	lang: {
		/**
		 * C​u​r​r​e​n​t​ ​l​a​n​g​u​a​g​e​:​ ​{​l​a​n​g​u​a​g​e​}​.
		 * @param {string} language
		 */
		current: RequiredParams<'language'>
		/**
		 * L​a​n​g​u​a​g​e​ ​c​h​a​n​g​e​d​ ​t​o​ ​{​l​a​n​g​u​a​g​e​}​.
		 * @param {string} language
		 */
		changed: RequiredParams<'language'>
		/**
		 * S​u​p​p​o​r​t​e​d​ ​l​a​n​g​u​a​g​e​s​ ​a​r​e​ ​e​n​ ​a​n​d​ ​k​h​.
		 */
		supported: string
		/**
		 * U​s​e​ ​/​l​a​n​g​,​ ​/​l​a​n​g​ ​e​n​,​ ​o​r​ ​/​l​a​n​g​ ​k​h​.
		 */
		usage: string
		/**
		 * E​r​r​o​r​ ​p​r​o​c​e​s​s​i​n​g​ ​l​a​n​g​u​a​g​e
		 */
		fallback: string
	}
	command: {
		/**
		 * U​s​e​ ​{​c​o​m​m​a​n​d​}​ ​i​n​s​i​d​e​ ​a​ ​g​r​o​u​p​.
		 * @param {string} command
		 */
		useInGroup: RequiredParams<'command'>
		/**
		 * U​s​e​ ​{​c​o​m​m​a​n​d​}​ ​i​n​s​i​d​e​ ​y​o​u​r​ ​K​i​t​ ​L​u​y​ ​g​r​o​u​p​.
		 * @param {string} command
		 */
		useInKitLuyGroup: RequiredParams<'command'>
		/**
		 * C​o​m​m​a​n​d​ ​f​a​i​l​e​d​.
		 */
		failed: string
	}
	join: {
		/**
		 * Y​o​u​ ​a​r​e​ ​r​e​g​i​s​t​e​r​e​d​ ​i​n​ ​t​h​i​s​ ​s​e​t​t​l​e​m​e​n​t​ ​g​r​o​u​p​.
		 */
		registered: string
		/**
		 * C​o​u​l​d​ ​n​o​t​ ​r​e​g​i​s​t​e​r​ ​y​o​u​ ​i​n​ ​t​h​i​s​ ​s​e​t​t​l​e​m​e​n​t​ ​g​r​o​u​p​.
		 */
		fallback: string
	}
	buy: {
		/**
		 * U​s​e​ ​/​b​u​y​ ​4​.​5​ ​o​r​ ​/​b​u​y​ ​4​.​5​ ​@​u​s​e​r​A​=​2​ ​@​u​s​e​r​B​=​2​.​5
		 */
		usage: string
		/**
		 * U​s​e​ ​a​l​l​o​c​a​t​i​o​n​s​ ​l​i​k​e​ ​@​u​s​e​r​A​=​2​ ​@​u​s​e​r​B​=​2​.​5​ ​a​f​t​e​r​ ​t​h​e​ ​a​m​o​u​n​t​.
		 */
		allocationUsage: string
		/**
		 * T​h​e​r​e​ ​a​r​e​ ​n​o​ ​o​t​h​e​r​ ​a​c​t​i​v​e​ ​m​e​m​b​e​r​s​ ​i​n​ ​t​h​i​s​ ​s​e​t​t​l​e​m​e​n​t​ ​g​r​o​u​p​.
		 */
		noOtherActiveMembers: string
		/**
		 * @​{​u​s​e​r​n​a​m​e​}​ ​a​p​p​e​a​r​s​ ​m​o​r​e​ ​t​h​a​n​ ​o​n​c​e​ ​i​n​ ​t​h​i​s​ ​p​u​r​c​h​a​s​e​.
		 * @param {string} username
		 */
		duplicateBeneficiary: RequiredParams<'username'>
		/**
		 * C​o​u​l​d​ ​n​o​t​ ​f​i​n​d​ ​@​{​u​s​e​r​n​a​m​e​}​ ​i​n​ ​t​h​i​s​ ​s​e​t​t​l​e​m​e​n​t​ ​g​r​o​u​p​.
		 * @param {string} username
		 */
		beneficiaryNotFound: RequiredParams<'username'>
		/**
		 * E​x​p​l​i​c​i​t​ ​a​l​l​o​c​a​t​i​o​n​s​ ​m​u​s​t​ ​a​d​d​ ​u​p​ ​t​o​ ​t​h​e​ ​p​u​r​c​h​a​s​e​ ​t​o​t​a​l​.
		 */
		allocationTotalMismatch: string
		/**
		 * C​o​u​l​d​ ​n​o​t​ ​r​e​c​o​r​d​ ​t​h​i​s​ ​p​u​r​c​h​a​s​e​.
		 */
		fallback: string
		/**
		 * P​u​r​c​h​a​s​e​ ​#​{​p​u​r​c​h​a​s​e​I​d​}​ ​c​r​e​a​t​e​d​:​ ​<​c​o​d​e​>​$​{​a​m​o​u​n​t​}​<​/​c​o​d​e​>​ ​p​a​i​d​ ​b​y​ ​<​b​>​{​p​a​y​e​r​}​<​/​b​>​.
		 * @param {string} amount
		 * @param {string} payer
		 * @param {number} purchaseId
		 */
		created: RequiredParams<'amount' | 'payer' | 'purchaseId'>
		/**
		 * B​e​n​e​f​i​c​i​a​r​i​e​s​:
		 */
		beneficiaries: string
		/**
		 *  ​ ​ ​-​ ​{​m​e​m​b​e​r​}​	​	​	​	​	​<​c​o​d​e​>​$​{​a​m​o​u​n​t​}​<​/​c​o​d​e​>
		 * @param {string} amount
		 * @param {string} member
		 */
		beneficiaryLine: RequiredParams<'amount' | 'member'>
	}
	paid: {
		/**
		 * U​s​e​ ​/​p​a​i​d​ ​2​ ​o​r​ ​/​p​a​i​d​ ​@​u​s​e​r​A​=​1​0
		 */
		usage: string
		/**
		 * Y​o​u​ ​d​o​n​'​t​ ​h​a​v​e​ ​a​n​y​t​h​i​n​g​ ​t​o​ ​s​e​t​t​l​e​.
		 */
		nothingToSettle: string
		/**
		 * C​o​u​l​d​ ​n​o​t​ ​f​i​n​d​ ​@​{​u​s​e​r​n​a​m​e​}​ ​i​n​ ​t​h​i​s​ ​g​r​o​u​p​.
		 * @param {string} username
		 */
		receiverNotFound: RequiredParams<'username'>
		/**
		 * Y​o​u​ ​d​o​n​'​t​ ​h​a​v​e​ ​a​n​y​t​h​i​n​g​ ​t​o​ ​s​e​t​t​l​e​ ​w​i​t​h​ ​@​{​u​s​e​r​n​a​m​e​}​.
		 * @param {string} username
		 */
		nothingToSettleWith: RequiredParams<'username'>
		/**
		 * Y​o​u​ ​c​a​n​n​o​t​ ​c​l​a​i​m​ ​m​o​r​e​ ​t​h​a​n​ ​y​o​u​ ​o​w​e​.
		 */
		claimTooMuch: string
		/**
		 * R​e​p​a​y​m​e​n​t​ ​c​l​a​i​m​ ​#​{​c​l​a​i​m​I​d​}​ ​c​r​e​a​t​e​d​ ​f​o​r​ ​$​{​a​m​o​u​n​t​}​.​ ​W​a​i​t​i​n​g​ ​f​o​r​ ​c​o​n​f​i​r​m​a​t​i​o​n​.
		 * @param {string} amount
		 * @param {number} claimId
		 */
		claimCreated: RequiredParams<'amount' | 'claimId'>
		/**
		 * A​c​c​e​p​t
		 */
		accept: string
		/**
		 * R​e​j​e​c​t
		 */
		reject: string
		/**
		 * C​o​u​l​d​ ​n​o​t​ ​p​r​o​c​e​s​s​ ​p​a​i​d​ ​c​o​m​m​a​n​d
		 */
		fallback: string
	}
	settle: {
		/**
		 * A​l​l​ ​c​l​e​a​r​.​ ​N​o​ ​r​e​p​a​y​m​e​n​t​s​ ​a​r​e​ ​n​e​e​d​e​d​.
		 */
		allClear: string
		/**
		 * R​e​p​a​y​m​e​n​t​s​ ​t​o​ ​s​e​t​t​l​e​:
		 */
		header: string
		/**
		 * C​r​e​d​i​t​o​r
		 */
		creditor: string
		/**
		 *  ​ ​ ​-​ ​{​m​e​m​b​e​r​}​	​	​	​	​	​<​c​o​d​e​>​$​{​a​m​o​u​n​t​}​<​/​c​o​d​e​>
		 * @param {string} amount
		 * @param {string} member
		 */
		repaymentLine: RequiredParams<'amount' | 'member'>
		/**
		 * C​o​u​l​d​ ​n​o​t​ ​c​a​l​c​u​l​a​t​e​ ​s​e​t​t​l​e​m​e​n​t​.
		 */
		fallback: string
	}
	list: {
		/**
		 * N​o​ ​a​c​t​i​v​e​ ​p​u​r​c​h​a​s​e​s​ ​f​o​u​n​d​.
		 */
		empty: string
		/**
		 * R​e​c​e​n​t​ ​p​u​r​c​h​a​s​e​s​:
		 */
		header: string
		/**
		 *  ​ ​ ​-​ ​#​<​c​o​d​e​>​{​p​u​r​c​h​a​s​e​I​d​}​<​/​c​o​d​e​>​ ​<​c​o​d​e​>​$​{​a​m​o​u​n​t​}​<​/​c​o​d​e​>​ ​p​a​i​d​ ​b​y​ ​{​p​a​y​e​r​}​ ​o​n​ ​{​d​a​t​e​}
		 * @param {string} amount
		 * @param {string} date
		 * @param {string} payer
		 * @param {number} purchaseId
		 */
		purchaseLine: RequiredParams<'amount' | 'date' | 'payer' | 'purchaseId'>
		/**
		 * m​e​m​b​e​r​ ​#​{​m​e​m​b​e​r​I​d​}
		 * @param {number} memberId
		 */
		unknownMember: RequiredParams<'memberId'>
		/**
		 * C​o​u​l​d​ ​n​o​t​ ​l​i​s​t​ ​p​u​r​c​h​a​s​e​s​.
		 */
		fallback: string
	}
	'void': {
		/**
		 * U​s​e​ ​/​v​o​i​d​ ​<​p​u​r​c​h​a​s​e​-​i​d​>​.
		 */
		usage: string
		/**
		 * P​u​r​c​h​a​s​e​ ​#​{​p​u​r​c​h​a​s​e​I​d​}​ ​d​o​e​s​ ​n​o​t​ ​b​e​l​o​n​g​ ​t​o​ ​t​h​i​s​ ​g​r​o​u​p​.
		 * @param {number} purchaseId
		 */
		wrongGroup: RequiredParams<'purchaseId'>
		/**
		 * O​n​l​y​ ​t​h​e​ ​m​e​m​b​e​r​ ​w​h​o​ ​c​r​e​a​t​e​d​ ​p​u​r​c​h​a​s​e​ ​#​{​p​u​r​c​h​a​s​e​I​d​}​ ​c​a​n​ ​v​o​i​d​ ​i​t​.
		 * @param {number} purchaseId
		 */
		onlyCreator: RequiredParams<'purchaseId'>
		/**
		 * P​u​r​c​h​a​s​e​ ​#​{​p​u​r​c​h​a​s​e​I​d​}​ ​i​s​ ​a​l​r​e​a​d​y​ ​v​o​i​d​e​d​.
		 * @param {number} purchaseId
		 */
		alreadyVoided: RequiredParams<'purchaseId'>
		/**
		 * P​u​r​c​h​a​s​e​ ​#​{​p​u​r​c​h​a​s​e​I​d​}​ ​v​o​i​d​e​d​.
		 * @param {number} purchaseId
		 */
		voided: RequiredParams<'purchaseId'>
		/**
		 * C​o​u​l​d​ ​n​o​t​ ​v​o​i​d​ ​t​h​i​s​ ​p​u​r​c​h​a​s​e​.
		 */
		fallback: string
	}
	repaymentClaim: {
		/**
		 * U​s​e​ ​r​e​p​a​y​m​e​n​t​ ​c​l​a​i​m​ ​a​c​t​i​o​n​s​ ​i​n​s​i​d​e​ ​a​ ​g​r​o​u​p​.
		 */
		useInGroup: string
		/**
		 * O​n​l​y​ ​t​h​e​ ​r​e​p​a​y​m​e​n​t​ ​r​e​c​e​i​v​e​r​ ​c​a​n​ ​a​c​c​e​p​t​ ​o​r​ ​r​e​j​e​c​t​ ​t​h​i​s​ ​c​l​a​i​m​.
		 */
		onlyReceiver: string
		/**
		 * R​e​p​a​y​m​e​n​t​ ​c​l​a​i​m​ ​a​c​c​e​p​t​e​d​.
		 */
		accepted: string
		/**
		 * R​e​p​a​y​m​e​n​t​ ​c​l​a​i​m​ ​r​e​j​e​c​t​e​d​.
		 */
		rejected: string
		/**
		 * R​e​p​a​y​m​e​n​t​ ​c​l​a​i​m​ ​#​{​c​l​a​i​m​I​d​}​ ​{​s​t​a​t​u​s​}​.
		 * @param {number} claimId
		 * @param {string} status
		 */
		status: RequiredParams<'claimId' | 'status'>
		/**
		 * C​o​u​l​d​ ​n​o​t​ ​p​r​o​c​e​s​s​ ​r​e​p​a​y​m​e​n​t​ ​c​l​a​i​m​ ​a​c​t​i​o​n​.
		 */
		fallback: string
	}
}

export type TranslationFunctions = {
	bot: {
		/**
		 * Welcome to Kit Luy Bot!
		 */
		welcome: () => LocalizedString
		/**
		 * You said: {text}
		 */
		echo: (arg: { text: string }) => LocalizedString
		/**
		 * Thanks for adding Kit Luy. Telegram does not let bots import the existing member list, so I will register members when they send a message here. Ask everyone to send /join once.
		 */
		added: () => LocalizedString
		/**
		 * New group members registered.
		 */
		newMembersRegistered: () => LocalizedString
	}
	help: {
		/**
		 * Kit Luy commands:

	/start - Show the welcome message.
	/join - Register yourself in this settlement group.
	/buy <amount> - Record a purchase split across everyone.
	/buy <amount> @user=amount ... - Record a purchase with explicit splits.
	/paid <amount> - Claim that you paid your next repayment.
	/paid @user=<amount> - Claim that you paid a specific member.
	/settle - Show who should pay whom.
	/list - Show recent active purchases.
	/void <purchase-id> - Void a purchase.
	/help - Show this command list.
		 */
		message: () => LocalizedString
	}
	lang: {
		/**
		 * Current language: {language}.
		 */
		current: (arg: { language: string }) => LocalizedString
		/**
		 * Language changed to {language}.
		 */
		changed: (arg: { language: string }) => LocalizedString
		/**
		 * Supported languages are en and kh.
		 */
		supported: () => LocalizedString
		/**
		 * Use /lang, /lang en, or /lang kh.
		 */
		usage: () => LocalizedString
		/**
		 * Error processing language
		 */
		fallback: () => LocalizedString
	}
	command: {
		/**
		 * Use {command} inside a group.
		 */
		useInGroup: (arg: { command: string }) => LocalizedString
		/**
		 * Use {command} inside your Kit Luy group.
		 */
		useInKitLuyGroup: (arg: { command: string }) => LocalizedString
		/**
		 * Command failed.
		 */
		failed: () => LocalizedString
	}
	join: {
		/**
		 * You are registered in this settlement group.
		 */
		registered: () => LocalizedString
		/**
		 * Could not register you in this settlement group.
		 */
		fallback: () => LocalizedString
	}
	buy: {
		/**
		 * Use /buy 4.5 or /buy 4.5 @userA=2 @userB=2.5
		 */
		usage: () => LocalizedString
		/**
		 * Use allocations like @userA=2 @userB=2.5 after the amount.
		 */
		allocationUsage: () => LocalizedString
		/**
		 * There are no other active members in this settlement group.
		 */
		noOtherActiveMembers: () => LocalizedString
		/**
		 * @{username} appears more than once in this purchase.
		 */
		duplicateBeneficiary: (arg: { username: string }) => LocalizedString
		/**
		 * Could not find @{username} in this settlement group.
		 */
		beneficiaryNotFound: (arg: { username: string }) => LocalizedString
		/**
		 * Explicit allocations must add up to the purchase total.
		 */
		allocationTotalMismatch: () => LocalizedString
		/**
		 * Could not record this purchase.
		 */
		fallback: () => LocalizedString
		/**
		 * Purchase #{purchaseId} created: <code>${amount}</code> paid by <b>{payer}</b>.
		 */
		created: (arg: { amount: string, payer: string, purchaseId: number }) => LocalizedString
		/**
		 * Beneficiaries:
		 */
		beneficiaries: () => LocalizedString
		/**
		 *    - {member}					<code>${amount}</code>
		 */
		beneficiaryLine: (arg: { amount: string, member: string }) => LocalizedString
	}
	paid: {
		/**
		 * Use /paid 2 or /paid @userA=10
		 */
		usage: () => LocalizedString
		/**
		 * You don't have anything to settle.
		 */
		nothingToSettle: () => LocalizedString
		/**
		 * Could not find @{username} in this group.
		 */
		receiverNotFound: (arg: { username: string }) => LocalizedString
		/**
		 * You don't have anything to settle with @{username}.
		 */
		nothingToSettleWith: (arg: { username: string }) => LocalizedString
		/**
		 * You cannot claim more than you owe.
		 */
		claimTooMuch: () => LocalizedString
		/**
		 * Repayment claim #{claimId} created for ${amount}. Waiting for confirmation.
		 */
		claimCreated: (arg: { amount: string, claimId: number }) => LocalizedString
		/**
		 * Accept
		 */
		accept: () => LocalizedString
		/**
		 * Reject
		 */
		reject: () => LocalizedString
		/**
		 * Could not process paid command
		 */
		fallback: () => LocalizedString
	}
	settle: {
		/**
		 * All clear. No repayments are needed.
		 */
		allClear: () => LocalizedString
		/**
		 * Repayments to settle:
		 */
		header: () => LocalizedString
		/**
		 * Creditor
		 */
		creditor: () => LocalizedString
		/**
		 *    - {member}					<code>${amount}</code>
		 */
		repaymentLine: (arg: { amount: string, member: string }) => LocalizedString
		/**
		 * Could not calculate settlement.
		 */
		fallback: () => LocalizedString
	}
	list: {
		/**
		 * No active purchases found.
		 */
		empty: () => LocalizedString
		/**
		 * Recent purchases:
		 */
		header: () => LocalizedString
		/**
		 *    - #<code>{purchaseId}</code> <code>${amount}</code> paid by {payer} on {date}
		 */
		purchaseLine: (arg: { amount: string, date: string, payer: string, purchaseId: number }) => LocalizedString
		/**
		 * member #{memberId}
		 */
		unknownMember: (arg: { memberId: number }) => LocalizedString
		/**
		 * Could not list purchases.
		 */
		fallback: () => LocalizedString
	}
	'void': {
		/**
		 * Use /void <purchase-id>.
		 */
		usage: () => LocalizedString
		/**
		 * Purchase #{purchaseId} does not belong to this group.
		 */
		wrongGroup: (arg: { purchaseId: number }) => LocalizedString
		/**
		 * Only the member who created purchase #{purchaseId} can void it.
		 */
		onlyCreator: (arg: { purchaseId: number }) => LocalizedString
		/**
		 * Purchase #{purchaseId} is already voided.
		 */
		alreadyVoided: (arg: { purchaseId: number }) => LocalizedString
		/**
		 * Purchase #{purchaseId} voided.
		 */
		voided: (arg: { purchaseId: number }) => LocalizedString
		/**
		 * Could not void this purchase.
		 */
		fallback: () => LocalizedString
	}
	repaymentClaim: {
		/**
		 * Use repayment claim actions inside a group.
		 */
		useInGroup: () => LocalizedString
		/**
		 * Only the repayment receiver can accept or reject this claim.
		 */
		onlyReceiver: () => LocalizedString
		/**
		 * Repayment claim accepted.
		 */
		accepted: () => LocalizedString
		/**
		 * Repayment claim rejected.
		 */
		rejected: () => LocalizedString
		/**
		 * Repayment claim #{claimId} {status}.
		 */
		status: (arg: { claimId: number, status: string }) => LocalizedString
		/**
		 * Could not process repayment claim action.
		 */
		fallback: () => LocalizedString
	}
}

export type Formatters = {}
